export const LOAD_USER_AZURE="LOAD_USER_AZURE"
export const LOAD_IS_AUTENTICATED="LOAD_IS_AUTENTICATED"
export const CHANGE_PRINTER_ADDRESS="CHANGE_PRINTER_ADDRESS"
export const CHANGE_PRINTER_ADDRESS_DEFAULT="CHANGE_PRINTER_ADDRESS_DEFAULT"
export const LOAD_SQL_DATA_USER="LOAD_SQL_DATA_USER"

export const CHANGE_IS_NEW_DAY="CHANGE_IS_NEW_DAY"